#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Realtime inference on Jetson Nano with a fine-tuned EfficientAT checkpoint.

Expected checkpoint format: the best_model.pt generated by
finetune_efficientat_kfold.py in the EdgeAudioRecognition Colab notebook.

Example inside Docker:
python3 -u jetson_live_finetuned.py \
  --checkpoint /workspace/EfficientAT/checkpoints/best_model_jetson.pt \
  --device plughw:2,0 \
  --rate 16000 \
  --channels 6 \
  --channel-index 0 \
  --seconds 2 \
  --topk 5 \
  --threshold 0.30
"""

from __future__ import print_function

import argparse
import contextlib
import os
import subprocess
import sys
import time
import wave

import numpy as np
import torch

TARGET_SR_DEFAULT = 32000
DBFS_FLOOR = -120.0
DEFAULT_DB_OFFSET = 80.0


class nullcontext(object):
    def __enter__(self):
        return None

    def __exit__(self, *args):
        return False


def amp_context(use_cuda, use_amp):
    if use_cuda and use_amp and hasattr(torch.cuda, "amp"):
        return torch.cuda.amp.autocast()
    return nullcontext()


def safe_torch_load(path, map_location):
    # PyTorch 1.10 on Jetson does not know the weights_only argument.
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)


def read_wav_select_channel(path, channel_index):
    with wave.open(path, "rb") as wf:
        sr = wf.getframerate()
        channels = wf.getnchannels()
        sampwidth = wf.getsampwidth()
        nframes = wf.getnframes()
        raw = wf.readframes(nframes)

    if sampwidth == 2:
        audio = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
    elif sampwidth == 4:
        audio = np.frombuffer(raw, dtype=np.int32).astype(np.float32) / 2147483648.0
    else:
        raise RuntimeError("Only 16-bit or 32-bit PCM WAV is supported.")

    if channels > 1:
        audio = audio.reshape(-1, channels)
        if channel_index == -1:
            audio = audio.mean(axis=1)
        else:
            if channel_index < 0 or channel_index >= channels:
                raise RuntimeError("channel_index is out of range: %s for %s channels" % (channel_index, channels))
            audio = audio[:, channel_index]
    return audio.astype(np.float32), sr, channels


def resample_linear(audio, src_sr, dst_sr):
    if src_sr == dst_sr:
        return audio.astype(np.float32)
    if len(audio) == 0:
        return audio.astype(np.float32)
    duration = len(audio) / float(src_sr)
    old_x = np.linspace(0.0, duration, num=len(audio), endpoint=False)
    new_len = int(round(duration * dst_sr))
    new_x = np.linspace(0.0, duration, num=new_len, endpoint=False)
    return np.interp(new_x, old_x, audio).astype(np.float32)


def calc_dbfs(audio):
    if audio is None or len(audio) == 0:
        return DBFS_FLOOR
    x = audio.astype(np.float64, copy=False)
    rms = float(np.sqrt(np.mean(x * x)))
    if rms <= 1e-12:
        return DBFS_FLOOR
    return float(20.0 * np.log10(rms))


def dbfs_to_display_db(dbfs, offset):
    value = float(dbfs) + float(offset)
    if value < 0:
        return 0.0
    return value


def prepare_clip(audio, sample_rate, clip_seconds, normalize=True):
    """Match the Colab training pipeline: mono, mean remove, peak normalize, pad/crop."""
    audio = np.asarray(audio, dtype=np.float32)
    clip_len = int(round(float(clip_seconds) * int(sample_rate)))
    if clip_len <= 0:
        raise RuntimeError("clip_seconds must be positive")
    if audio.size == 0:
        audio = np.zeros((clip_len,), dtype=np.float32)

    if normalize:
        audio = audio - float(audio.mean())
        peak = float(np.max(np.abs(audio))) if audio.size else 0.0
        if peak < 1e-5:
            peak = 1e-5
        audio = np.clip(audio / peak, -1.0, 1.0).astype(np.float32)

    n = int(audio.shape[0])
    if n < clip_len:
        audio = np.pad(audio, (0, clip_len - n), mode="constant")
    elif n > clip_len:
        start = (n - clip_len) // 2
        audio = audio[start:start + clip_len]
    return audio.astype(np.float32)


def ensure_repo_on_path(efficientat_dir):
    efficientat_dir = os.path.abspath(efficientat_dir)
    if not os.path.isdir(efficientat_dir):
        raise RuntimeError("EfficientAT directory not found: %s" % efficientat_dir)
    if efficientat_dir not in sys.path:
        sys.path.insert(0, efficientat_dir)
    os.chdir(efficientat_dir)


def infer_num_classes_from_state(state_dict):
    for key in ["classifier.5.bias", "classifier.1.bias"]:
        if key in state_dict:
            return int(state_dict[key].numel())
    # Fallback: find a final classifier bias-like vector.
    candidates = []
    for k, v in state_dict.items():
        if k.startswith("classifier") and hasattr(v, "ndim") and v.ndim == 1:
            candidates.append((k, int(v.numel())))
    if candidates:
        candidates.sort()
        return candidates[-1][1]
    raise RuntimeError("Could not infer num_classes from checkpoint. Need labels in checkpoint.")


def load_finetuned_model(checkpoint_path, efficientat_dir, device, override_model_name=None, override_head_type=None, quiet=True):
    ensure_repo_on_path(efficientat_dir)
    from helpers.utils import NAME_TO_WIDTH  # noqa
    from models.mn.model import get_model as get_mobilenet  # noqa
    from models.preprocess import AugmentMelSTFT  # noqa

    ckpt = safe_torch_load(checkpoint_path, map_location=torch.device("cpu"))
    if isinstance(ckpt, dict) and "model_state_dict" in ckpt:
        state_dict = ckpt["model_state_dict"]
        cfg = ckpt.get("config", {}) or {}
        labels = ckpt.get("labels", None)
    else:
        state_dict = ckpt
        cfg = {}
        labels = None

    num_classes = len(labels) if labels else infer_num_classes_from_state(state_dict)
    if not labels:
        labels = ["class_%d" % i for i in range(num_classes)]

    model_name = override_model_name or cfg.get("model_name", "mn04_as")
    head_type = override_head_type or cfg.get("head_type", "mlp")
    sample_rate = int(cfg.get("sample_rate", TARGET_SR_DEFAULT))
    clip_seconds = float(cfg.get("clip_seconds", 10.0))

    # Important: pretrained_name=None avoids internet/download on Jetson.
    if quiet:
        with open(os.devnull, "w") as devnull, contextlib.redirect_stdout(devnull):
            model = get_mobilenet(
                num_classes=num_classes,
                pretrained_name=None,
                width_mult=NAME_TO_WIDTH(model_name),
                head_type=head_type,
            )
    else:
        model = get_mobilenet(
            num_classes=num_classes,
            pretrained_name=None,
            width_mult=NAME_TO_WIDTH(model_name),
            head_type=head_type,
        )

    model.load_state_dict(state_dict, strict=True)
    model.to(device)
    model.eval()

    mel = AugmentMelSTFT(
        n_mels=128,
        sr=sample_rate,
        win_length=800,
        hopsize=320,
        freqm=0,
        timem=0,
    )
    mel.to(device)
    mel.eval()

    meta = {
        "model_name": model_name,
        "head_type": head_type,
        "sample_rate": sample_rate,
        "clip_seconds": clip_seconds,
        "num_classes": num_classes,
        "labels": labels,
    }
    return model, mel, labels, meta


def predict_one(model, mel, audio_np, device, use_cuda, use_amp):
    waveform = torch.from_numpy(audio_np[None, :]).to(device)
    if use_cuda:
        torch.cuda.synchronize()
    t0 = time.time()
    with torch.no_grad(), amp_context(use_cuda, use_amp):
        spec = mel(waveform)
        out = model(spec.unsqueeze(1))
        logits = out[0] if isinstance(out, (tuple, list)) else out
        if logits.dim() == 1:
            logits = logits.unsqueeze(0)
        probs = torch.softmax(logits.float(), dim=-1).squeeze(0)
    if use_cuda:
        torch.cuda.synchronize()
    t1 = time.time()
    return probs.detach().cpu().numpy(), t1 - t0


def record_chunk(args, wav_path):
    cmd = [
        "arecord",
        "-q",
        "-D", args.device,
        "-f", "S16_LE",
        "-r", str(args.rate),
        "-c", str(args.channels),
        "-d", str(args.seconds),
        wav_path,
    ]
    return subprocess.call(cmd)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", required=True, help="Path to best_model_jetson.pt or best_model.pt")
    parser.add_argument("--efficientat-dir", default="/workspace/EfficientAT")
    parser.add_argument("--device", required=True, help="ALSA device, e.g. plughw:2,0")
    parser.add_argument("--model-name", default=None, help="Override checkpoint config, usually not needed")
    parser.add_argument("--head-type", default=None, help="Override checkpoint config, usually not needed")
    parser.add_argument("--rate", type=int, default=16000)
    parser.add_argument("--channels", type=int, default=6)
    parser.add_argument("--channel-index", type=int, default=0, help="0=first channel, -1=average all channels")
    parser.add_argument("--seconds", type=int, default=2, help="recording length per realtime decision")
    parser.add_argument("--clip-seconds", type=float, default=None, help="model input length; default from checkpoint, usually 10")
    parser.add_argument("--topk", type=int, default=5)
    parser.add_argument("--threshold", type=float, default=0.70, help="softmax score threshold")
    parser.add_argument("--min-db", type=float, default=45.0, help="skip inference below this display dB")
    parser.add_argument("--db-offset", type=float, default=DEFAULT_DB_OFFSET, help="display_dB = dBFS + offset")
    parser.add_argument("--db-threshold", type=float, default=None, help="legacy dBFS threshold; use --min-db instead")
    parser.add_argument("--print-skipped", action="store_true")
    parser.add_argument("--cpu", action="store_true")
    parser.add_argument("--amp", action="store_true", help="enable cuda amp; off by default for Jetson stability")
    parser.add_argument("--no-normalize", action="store_true", help="disable training-style mean/peak normalization")
    parser.add_argument("--show-model", action="store_true")
    args = parser.parse_args()

    use_cuda = (not args.cpu) and torch.cuda.is_available()
    device = torch.device("cuda" if use_cuda else "cpu")

    if args.db_threshold is not None:
        if args.db_threshold < 0:
            min_db = args.db_threshold + args.db_offset
        else:
            min_db = args.db_threshold
    else:
        min_db = args.min_db

    torch.backends.cudnn.benchmark = False

    model, mel, labels, meta = load_finetuned_model(
        args.checkpoint,
        args.efficientat_dir,
        device,
        override_model_name=args.model_name,
        override_head_type=args.head_type,
        quiet=(not args.show_model),
    )
    sample_rate = int(meta["sample_rate"])
    clip_seconds = float(args.clip_seconds if args.clip_seconds is not None else meta["clip_seconds"])

    print("device:", device)
    print("checkpoint:", args.checkpoint)
    print("model:", meta["model_name"], "head:", meta["head_type"], "classes:", meta["num_classes"])
    print("labels:", ", ".join(labels))
    print("audio device:", args.device)
    print("record: %sHz, %sch, %ss" % (args.rate, args.channels, args.seconds))
    print("channel-index:", args.channel_index)
    print("model input: %sHz, %.2fs" % (sample_rate, clip_seconds))
    print("score: softmax, threshold=%.3f" % args.threshold)
    print("min-db: %.1f dB" % min_db)
    print("Ctrl+C to stop")
    print("-" * 60)

    wav_path = "/tmp/respeaker_finetuned_chunk.wav"
    while True:
        loop_start = time.time()
        rc = record_chunk(args, wav_path)
        if rc != 0:
            print("arecord failed. Check --device, --rate, --channels.", flush=True)
            time.sleep(1)
            continue

        audio, src_sr, detected_channels = read_wav_select_channel(wav_path, args.channel_index)
        audio = resample_linear(audio, src_sr, sample_rate)

        dbfs = calc_dbfs(audio)
        display_db = dbfs_to_display_db(dbfs, args.db_offset)
        if display_db <= min_db:
            total_time = time.time() - loop_start
            # UI needs a fresh event so it does not keep showing the previous class.
            print(
                "[%s] infer=0.000s total=%.3fs db=%.1fdB | listening 0.000" % (
                    time.strftime("%H:%M:%S"), total_time, display_db
                ),
                flush=True,
            )
            continue

        clip = prepare_clip(audio, sample_rate, clip_seconds, normalize=(not args.no_normalize))
        scores, infer_time = predict_one(model, mel, clip, device, use_cuda, args.amp)
        total_time = time.time() - loop_start

        sorted_idx = np.argsort(scores)[::-1]
        shown = []
        for idx in sorted_idx[:args.topk]:
            score = float(scores[idx])
            if score >= args.threshold:
                shown.append("%s %.3f" % (labels[idx], score))
        if len(shown) == 0:
            # Do not expose a class below the UI confidence threshold.
            shown.append("listening 0.000")

        print(
            "[%s] infer=%.3fs total=%.3fs db=%.1fdB | %s" % (
                time.strftime("%H:%M:%S"), infer_time, total_time, display_db, " / ".join(shown)
            ),
            flush=True,
        )


if __name__ == "__main__":
    main()
